version: 1.0.{build}

clone_folder: C:\block\Str

build:

install:
    - git submodule -q update --init --recursive

build_script:
    - cd C:\block\Str
    - md build
    - cd build
    - cmake -G"Visual Studio 14 2015 Win64" ..
    - cmake --build . --config debug

after_build:

test_script:
    - cmd: ctest -C Debug -VV
